
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Bruno Song')
Visualization.create!(path: './music/color.mp3', name: 'King Koopa')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Crab')
Visualization.create!(path: './music/color.mp3', name: 'Tunis')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Soojeen')
Visualization.create!(path: './music/color.mp3', name: 'Abhi')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Codester')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Andrew')
Visualization.create!(path: './music/color.mp3', name: 'Wingnut')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Crabito')
Visualization.create!(path: './music/color.mp3', name: 'Gargle')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'Squids')
Visualization.create!(path: './music/color.mp3', name: 'Sally')
Visualization.create!(path: './music/Lenno-Lost.mp3', name: 'SantaClause')